const express = require('express');
const app = express();
const PORT = 5000;


app.get('/api', (req, res) => {
    res.json({users: [{"username":"gestevez0","email":"bdepinna0@artisteer.com","password":"jH7`rwwy","date_of_birth":"12/26/1993","gender":"Female","location":"Casselman","bio":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus."},
    {"username":"benrico1","email":"sbutteris1@hp.com","password":"rG9+()2ZxMI\\`nE","date_of_birth":"11/16/1986","gender":"Male","location":"Aībak","bio":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem."},
    {"username":"acurl2","email":"hquenby2@desdev.cn","password":"zA1',EK'$","date_of_birth":"3/8/1991","gender":"Genderqueer","location":"Alto Barinas","bio":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem."},
    {"username":"gsimonett3","email":"bkerbey3@amazon.de","password":"eL5>bQ\"Ze","date_of_birth":"7/16/1983","gender":"Male","location":"Casal do Sapo","bio":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem."},
    {"username":"mbarbary4","email":"ahordle4@istockphoto.com","password":"vD7)@?2J","date_of_birth":"8/25/2000","gender":"Female","location":"Sidaurip","bio":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem."},
    {"username":"eplayer5","email":"cyurkov5@icq.com","password":"lD6|ikSd@4E","date_of_birth":"6/23/1997","gender":"Genderfluid","location":"Magway","bio":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque."},
    {"username":"tmenico6","email":"ctampen6@buzzfeed.com","password":"tI5?neC.{/h.<1","date_of_birth":"7/9/2000","gender":"Male","location":"Kobeřice","bio":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus."},
    {"username":"jtullett7","email":"hlacase7@meetup.com","password":"aR2~pEIf/XmeW","date_of_birth":"8/3/1988","gender":"Male","location":"Balangonan","bio":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus."},
    {"username":"kbowld8","email":"bparlet8@ocn.ne.jp","password":"jI9?1r/V@`yvNJH(","date_of_birth":"12/6/1994","gender":"Female","location":"Saihan Tal","bio":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem."},
    {"username":"kscroyton9","email":"ntoplis9@irs.gov","password":"pN8_<M69)<(bXE$","date_of_birth":"6/14/1980","gender":"Male","location":"Osorno","bio":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus."}]}
        )})

app.listen(PORT, console.log('servidor node por el puerto ${PORT}'));